# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: be9014f6470f214158f3702e4392d4a4998b5cf4ca4cadac6ebed061a1444d0f3669b6a3f0e346fa204ec0d439012a9e74de865acd5daa25568adea4f11af508

test:
  secret_key_base: d279775cda1d6a6d9c57c9166e41f27ba4b09c677b044d87ca2de8175e9761183e719ced03a3b95cafab5b03e2b6a682edce0782a69a6bd53c09293dbc30d7af

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
